version: "3.9"

services:
  db:
    build:
        context: .
        dockerfile: postgresql.Dockerfile
    container_name: postgres-db
    restart: always
    volumes:
    - './postgres_data:/var/lib/postgresql/data'
    env_file:
      - .env.postgresql
    ports:
    - '5433:5432'